# Default server configuration.
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/angel
port: 3000
jwt_secret: 'oKJYqbI1MGENg9f6W9LVJKSS8EusrYzY'
postgres:
  host: ec2-176-34-97-213.eu-west-1.compute.amazonaws.com
  port: 5432
  database_name: d6vg95vhbt58n3
  username: fgkxsdrduyfugn
  password: 32e77641a5a9c3459397d7d389b713c962bb019d5bb01a682ebfdc7852684526
  use_ssl: true
