name: server
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  # Angel
  angel_auth: ^2.0.0 # Supports stateless authentication via JWT
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.0 # The core server library.
  angel_graphql: ^1.0.0 # Infrastructure for serving GraphQL.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_production: ^1.0.0 # Production application runner.
  angel_static: ^2.0.0 # Static file server
  angel_validate: ^2.0.0 # Allows for validation of input data
  angel_orm: ^2.0.0 # Migration runtime support
  angel_orm_postgres: ^1.0.0 # PostgreSQL support for Angel ORM
  angel_migration: ^2.0.0 # A PostgreSQL database migration framework built on Angel's ORM.
  angel_orm_service: ^1.0.0 # Service implementation that wraps over Angel ORM Query classes.
  angel_migration_runner: ^2.0.0
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_serialize_generator: ^2.0.0 # Generates serialization code, and more.
  angel_test: ^2.0.0 # Utilities for testing Angel servers.
  build_runner: ^1.0.0 # Runs code builders.
  graphql_generator: ^1.0.0 # Generates GraphQL schemas statically.
  io: ^0.3.2 # For pretty printing.
  pedantic: ^1.0.0 # Enforces Dart style conventions.
  test: ^1.0.0 # For unit testing.
  angel_orm_generator: ^2.0.0
dependency_overrides:
  postgres: 2.1.1
  graphql_server:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/graphql/graphql_server
  graphql_parser:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/graphql/graphql_parser
  angel_orm:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/orm/angel_orm
  angel_orm_service:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/orm/angel_orm_service
  angel_orm_postgres:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/orm/angel_orm_postgres
  angel_graphql:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/graphql/angel_graphql
  graphql_generator:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/graphql/graphql_generator
  # angel_orm_generator:
  #   git:
  #     url: https://github.com/angel-dart/angel.git
  #     path: packages/orm/angel_orm_generator
  angel_serialize_generator:
    git:
      url: https://github.com/angel-dart/angel.git
      path: packages/serialize/angel_serialize_generator
